# Generated by Django 5.2.9 on 2025-12-18 02:09

import django.db.models.deletion
import sites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="サイトタイトル"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "サイト",
                "verbose_name_plural": "サイト",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MainSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="タイトル"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="サブタイトル"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="main/",
                        validators=[sites.models.validate_image_extension],
                        verbose_name="画像1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="main/",
                        validators=[sites.models.validate_image_extension],
                        verbose_name="画像2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="main/",
                        validators=[sites.models.validate_image_extension],
                        verbose_name="画像3",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_section",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "メインセクション",
                "verbose_name_plural": "メインセクション",
            },
        ),
        migrations.CreateModel(
            name="AccessSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        default="アクセス",
                        max_length=100,
                        verbose_name="セクションタイトル",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="住所"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "business_hours",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='例: [{"day": "月-金", "hours": "9:00-18:00"}, {"day": "土日祝", "hours": "定休日"}]',
                        verbose_name="営業時間",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_section",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "アクセスセクション",
                "verbose_name_plural": "アクセスセクション",
            },
        ),
        migrations.CreateModel(
            name="SubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sub/",
                        validators=[sites.models.validate_image_extension],
                        verbose_name="画像1",
                    ),
                ),
                ("text1", models.TextField(blank=True, verbose_name="テキスト1")),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sub/",
                        validators=[sites.models.validate_image_extension],
                        verbose_name="画像2",
                    ),
                ),
                ("text2", models.TextField(blank=True, verbose_name="テキスト2")),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sub/",
                        validators=[sites.models.validate_image_extension],
                        verbose_name="画像3",
                    ),
                ),
                ("text3", models.TextField(blank=True, verbose_name="テキスト3")),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_section",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "サブセクション",
                "verbose_name_plural": "サブセクション",
            },
        ),
        migrations.CreateModel(
            name="TopSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="top/",
                        validators=[sites.models.validate_image_extension],
                        verbose_name="ヒーロー画像",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_section",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "トップセクション",
                "verbose_name_plural": "トップセクション",
            },
        ),
        migrations.CreateModel(
            name="SectionStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        choices=[
                            ("top", "トップ"),
                            ("main", "メイン"),
                            ("sub", "サブ"),
                            ("access", "アクセス"),
                        ],
                        max_length=20,
                        verbose_name="セクション名",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#FFFFFF", max_length=7, verbose_name="背景色"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="文字色"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Noto Sans JP", max_length=100, verbose_name="フォント"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_styles",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "セクションスタイル",
                "verbose_name_plural": "セクションスタイル",
                "unique_together": {("site", "section_name")},
            },
        ),
        migrations.CreateModel(
            name="SNSLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("x", "X (Twitter)"),
                            ("line", "LINE"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                        verbose_name="プラットフォーム",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sns_links",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "SNSリンク",
                "verbose_name_plural": "SNSリンク",
                "unique_together": {("site", "platform")},
            },
        ),
    ]
