# Generated by Django 5.2.9 on 2025-12-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainsection",
            name="image_fit",
            field=models.CharField(
                choices=[
                    ("cover", "カバー（トリミング）"),
                    ("contain", "全体表示"),
                    ("fill", "引き伸ばし"),
                ],
                default="cover",
                max_length=20,
                verbose_name="画像表示モード",
            ),
        ),
        migrations.AddField(
            model_name="mainsection",
            name="image_height",
            field=models.IntegerField(default=400, verbose_name="画像高さ(px)"),
        ),
        migrations.AddField(
            model_name="subsection",
            name="image_fit",
            field=models.CharField(
                choices=[
                    ("cover", "カバー（トリミング）"),
                    ("contain", "全体表示"),
                    ("fill", "引き伸ばし"),
                ],
                default="cover",
                max_length=20,
                verbose_name="画像表示モード",
            ),
        ),
        migrations.AddField(
            model_name="subsection",
            name="image_height",
            field=models.IntegerField(default=256, verbose_name="画像高さ(px)"),
        ),
        migrations.AddField(
            model_name="topsection",
            name="hero_image_fit",
            field=models.CharField(
                choices=[
                    ("cover", "カバー（トリミング）"),
                    ("contain", "全体表示"),
                    ("fill", "引き伸ばし"),
                ],
                default="cover",
                max_length=20,
                verbose_name="画像表示モード",
            ),
        ),
        migrations.AddField(
            model_name="topsection",
            name="hero_image_height",
            field=models.IntegerField(default=500, verbose_name="画像高さ(px)"),
        ),
    ]
