# Generated by Django 5.2.9 on 2025-12-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_mainsection_image_fit_mainsection_image_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionstyle",
            name="text_align",
            field=models.CharField(
                choices=[
                    ("text-left", "左揃え"),
                    ("text-center", "中央揃え"),
                    ("text-right", "右揃え"),
                ],
                default="text-left",
                max_length=20,
                verbose_name="文字配置",
            ),
        ),
        migrations.AddField(
            model_name="sectionstyle",
            name="text_size",
            field=models.CharField(
                choices=[
                    ("text-sm", "小"),
                    ("text-base", "中"),
                    ("text-lg", "大"),
                    ("text-xl", "特大"),
                    ("text-2xl", "極大"),
                ],
                default="text-base",
                max_length=20,
                verbose_name="文字サイズ",
            ),
        ),
    ]
