# Generated by Django 5.2.9 on 2025-12-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_sectionstyle_text_align_sectionstyle_text_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionstyle",
            name="text_size",
            field=models.IntegerField(default=16, verbose_name="文字サイズ(px)"),
        ),
    ]
